### ISSUE TITLE
_app ve _document in en ustune react importu alabiliriz

### ISSUE THREAD

**Issue by aliemir** [pankod/next-cli#49]
daha sonrasinda eklenen pluginler _app veya _document icinde react gerektiren bir degisiklik yaptiginda problem olabiliyor.

belki de bu importu plugin in extend.js ine birakabiliriz bu durumda da yapilan importlari kontrol etmemiz gerekir tekrar etmemeleri icin.

**Comment by omeraplak** [comment]
bence alalım. İlla react import edilecektir
