### ISSUE TITLE
Bu CLI tool'unun amacı nedir?

### ISSUE THREAD

**Issue by aykutkardas** [pankod/next-cli#57]
README çok açıklayıcı olmadı benim için. Sanırım erken bir sahfada keşfettim repoyu.

**Comment by omeraplak** [comment]
Aykut merhaba,
CLI henuz development asamasinda. Yakin zamanda release etmeyi planliyoruz. Ilgin icin cok tesekkurler :)

**Comment by aykutkardas** [comment]
> Aykut merhaba,
> CLI henuz development asamasinda. Yakin zamanda release etmeyi planliyoruz. Ilgin icin cok tesekkurler :)

Public bir repo olduğu için hedeflerinizi bilirsem katkıda bulunabilirim.

**Comment by omeraplak** [comment]
Proje henüz erken bir safhasında bu yüzden kolayca katkı sağlanabilecek durumda değil. Release sonrası mutlaka katkılarını bekliyor olacağız :)
